### ISSUE TITLE
data dictionary for dataframe objects in MidiFramer

### ISSUE THREAD

**Issue by softloud** [urswilke/pyramidi#7]
Thank you for this package :) 

I was an acoustic musician in a previous life, now a math nerd data scientist. This is the first time I've worked with midi data. Using music theory, I'm making sense of the `note` and `b` columns, however I think as I progress with this project, I suspect I'll end up reinventing the wheel without understanding all the columns output in the dataframes provided. 

Could you please point me to documentation that will help me understand what the columns are in the various objects output by the midi transformations provided? Apologies if this is super obvious in the documentation and I failed to see it.

**Comment by urswilke** [comment]
Thank you for using the package! :)

The documentation could definitely be better... Does [this](https://urswilke.github.io/pyramidi/articles/functions_usage.html#translate-midi-time-information) help you?

**Comment by softloud** [comment]
Thank you! aha, yes, very useful, and shows me what I don't need to engineer 👍 

Am exploring animation of directed graphs of music - here's my first plot, using a midi file from wikipedia of the subject of Contrapunctus I by Bach (I played it for my final high school recital decades ago) - taking pyramidi dataframe and apply ggraph, you'll likely hear from me again, am just getting started. 
![firsttrytab](https://github.com/urswilke/pyramidi/assets/13408706/30b2da7c-6c7e-49e5-81a8-d98a4a258090)
![firsttry](https://github.com/urswilke/pyramidi/assets/13408706/fc74e318-a490-40a5-9102-8b0ae517489d)

**Comment by softloud** [comment]
Bonus points for tips on how to get note labelling by key, atm am engineering myself.

**Comment by urswilke** [comment]
I don't know if there are R packages to label the notes according to a key. Otherwise, you could write the note names into a data.frame (in the format of `pyramidi::midi_defs`) and then merge this information to the pyramidi data.frame by midi `note`.
